### bruteforce.R
# This script uses one of the combination tables
# (e.g., Table_3.tsv, ...) generated by generate.R to
# brute force calculate the best score.

# library imports
library(dplyr)

# define file names
m_filename <- file.path("examples", "3c", "m.tsv")
f_filename <- file.path("examples", "3c", "f.tsv")
m_x_m_filename <- file.path("examples", "3c", "m_x_m.tsv")
f_x_f_filename <- file.path("examples", "3c", "f_x_f.tsv")
mf_combs_filename <- file.path("output", "table_3.tsv")

# load files
m <- read.delim(m_filename, header = FALSE)
f <- read.delim(f_filename, header = FALSE)
m_x_m <- read.delim(m_x_m_filename, row.names = 1)
f_x_f <- read.delim(f_x_f_filename, row.names = 1)
mf_combs <- read.delim(mf_combs_filename)

# calculate the score for each combination
# we will use calculate_score from calculate_rscore.R (thanks Faris)
source("R/rscore_functions.R")
score_list <- vector("numeric", nrow(mf_combs))
for (i in 1:nrow(mf_combs)) {
  score_list[i] <- calculate_score(mf_combs[i,])
}

score_result <- data.frame(mf_combs, score_list)

bruteforce_df = data.frame(
  c1a = integer(),
  c1b = integer(),
  c2a = integer(),
  c2b = integer(),
  c3a = integer(),
  c3b = integer()
)

scores_df = data.frame(
  c1 = double(),
  c2 = double(),
  c3 = double(),
  total = double()
)

# look for all possible combinations
for (i in 1:nrow(score_result)) {
  # first combination is our starting point
  c1a = score_result[i,]$mfcomb1
  c1b = score_result[i,]$mfcomb2
  c1s = score_result[i,]$score_list
  
  # find combinations which also include C1,
  # with exception of its own
  mf_combs_c1 = score_result %>%
    slice(-(i)) %>%
    filter(mfcomb1 == c1a | mfcomb2 == c1a)
  
  for (i in 1:nrow(mf_combs_c1)) {
    c2a = mf_combs_c1[i,]$mfcomb1
    c2b = mf_combs_c1[i,]$mfcomb2
    c2s = mf_combs_c1[i,]$score_list
    
    comb = c(c1a, c1b, c2a, c2b)
    comb_unique = comb[!(comb %in% comb[duplicated(comb)])]
    
    mf_combs_c2 = score_result %>%
      filter((mfcomb1 == comb_unique[1] &
                mfcomb2 == comb_unique[2]) |
               (mfcomb1 == comb_unique[2] &
                  mfcomb2 == comb_unique[1])
      )
    
    if (nrow(mf_combs_c2) == 0) {
      next
    }
    
    for (i in 1:nrow(mf_combs_c2)) {
      c3a = mf_combs_c2[i,]$mfcomb1
      c3b = mf_combs_c2[i,]$mfcomb2
      c3s = mf_combs_c2[i,]$score_list
      
      comb = c(c1a, c1b, c2a, c2b, c3a, c3b)
      scores = c(c1s, c2s, c3s)
    
      bruteforce_df[nrow(bruteforce_df) + 1, ] = comb
      scores_df[nrow(scores_df) + 1, ] = c(scores, prod(scores))
      
    }
    
  }
}

bruteforce_df = bruteforce_df[!duplicated(bruteforce_df), ]
scores_df = scores_df[!duplicated(scores_df), ]

# generate output files
write.table(
  bruteforce_df,
  file = file.path("output", "bruteforce", "combinations_3d.tsv") ,
  sep = "\t",
  row.names = FALSE
)

write.table(
  scores_df,
  file = file.path("output", "bruteforce", "scores_3d.tsv") ,
  sep = "\t",
  row.names = FALSE
)

# generate plots
source("R/plot_rscore_comb.R")
for (i in 1:nrow(bruteforce_df)) {
  combs = as.character(bruteforce_df[i, ])
  scores = as.numeric(scores_df[i, ])
  fname = file.path("output", "bruteforce", "plots_3d",
                    paste0(i, ".png"))
  
  save_and_plot_rscore_combination(combs, scores, fname)
}
  